export const INJECTION_TOKENS = {
  SELECTOR_REPOSITORY: 'SELECTOR_REPOSITORY',
  BROWSER_CLIENT: 'BROWSER_CLIENT',
  AI_CLIENT: 'AI_CLIENT',
  /** @deprecated Use SELECTOR_REPOSITORY instead */
  XPATH_REPOSITORY: 'SELECTOR_REPOSITORY',
} as const;
